export enum Screens {
  HOME_SCREEN = "HOME_SCREEN",
  LOBBY_SCREEN = "LOBBY_SCREEN",
  GAME_SCREEN = "GAME_SCREEN",
  CHARACTER_SELECT_SCREEN = "CHARACTER_SELECT_SCREEN",
  WAITING_SCREEN = "WAITING_SCREEN",
  DUEL_WAITING_SCREEN = "DUEL_WAITING_SCREEN",
  LEVEL_SELECT_SCREEN = "LEVEL_SELECT_SCREEN",
}
